apiVersion: v1
kind: Service
metadata:
  name: dc-frontend
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: dc-frontend
  ports:
    - name: http
      port: 4004
      targetPort: 4004
      protocol: TCP
